# Generated by Django 3.2 on 2022-01-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220121_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='imageURLs',
        ),
    ]
