# Generated by Django 3.2 on 2022-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_url_product_imageurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageURLs',
            new_name='image_url',
        ),
    ]
